<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <NoWarn>MSB3277</NoWarn>
    <ReloadedILLink>false</ReloadedILLink>
    <AssemblyName>FFTTreasureMaster</AssemblyName>
    <RootNamespace>FFTTreasureMaster</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Reloaded.Mod.Interfaces" Version="2.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="fftivc.utility.modloader.Interfaces" Version="1.6.1" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <None Include="treasure.json" CopyToOutputDirectory="PreserveNewest" Condition="Exists('treasure.json')" />
  </ItemGroup>

</Project>
